version: '3'

services:
  server-nginx:
    container_name: web-server-cursos
    build: infra/web-server/nginx
    ports:
      - "88:80"
    volumes:
      - ./projetos/:/var/www/
    tty: true
    networks:
      - cursos-network

  server-mysql:
    container_name: data-base-cursos
    build: infra/data-base/mysql-5.7.22
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: cursos-laravel
     MYSQL_DATABASE: cursos-laravel
     MYSQL_USER: cursos-laravel
     MYSQL_PASSWORD: cursos-laravel
    networks:
     - cursos-network

#  server-elasticsearch:
#    container_name: elasticsearch-cursos
#    build: infra/log/elasticsearch
#    ports:
#     - "9200:9200"
#    volumes:
#      - ./infra/log/elasticsearch/els-data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#    networks:
#     - cursos-network

#  server-kibana:
#    container_name: kibana-cursos
#    build: infra/log/kibana
#    ports:
#      - "5601:5601"
#    networks:
#      - cursos-network

#  server-logstash:
#    container_name: logstash-cursos
#    build: infra/log/logstash
#    #tty: true
#    ports:
#      - "5044:5044"
#    networks:
#      - cursos-network

networks:
  cursos-network:
    driver: bridge